name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: lein deps
    - name: Run Linter 
      run: lein eastwood
    - name: Run Formatter
      run: lein cljfmt check
    - name: Run Static Analysis
      run: lein kibit
    - name: Run tests
      run: lein test
